### ISSUE TITLE
Support for Constants in build file

### ISSUE THREAD

**Issue by brian-bason** [brian-bason/docker-build-tool#10]
It would be good to support constants within a build file so that they can be used throughout the build. The concept is the same as the arguments but the value of the constant would not be updated from outside the build file.

**Comment by johndavidpearce** [comment]
Just worth noting here that YAML has limited support for referring to previously defined objects.

```
_const1: &const1 "Some value"
STEPS:
  - CONFIG:
      CMD:
        - --arg-key
        - *const1
```

This would only work for some situations where the string concatenation behaviour supported by arguments is not required (such as passing in the value of a constant as a value to the `CMD` list).
