### ISSUE TITLE
Support of Choices list of Arguments

### ISSUE THREAD

**Issue by brian-bason** [brian-bason/docker-build-tool#2]
It would be great to include a Choice option for Arguments so that one can limit what value is accepted for that argument. The creator of the Docker-Build file can then specify a list of values that are valid for that argument. If an invalid value is given for the argument the build should fail.

Example

```
ARGS:
  INSTANCE_TYPE:
    CHOICES:
      - server
      - client
```
