### ISSUE TITLE
Add "info" command to inspect a build file

### ISSUE THREAD

**Issue by johndavidpearce** [brian-bason/docker-build-tool#23]
This should parse the build configuration file and produce a summary of build usage for this particular configuration.

```build-tool info```

Given a configuration file like:

```
VERSION: "1.0"
DESCRIPTION: "Hello world application"
ARGS:
  AUTHOR:
    DESCRIPTION: "The name of the author of this image"
    REQUIRED: True
  USER:
    DESCRIPTION: "The person who is being greeted"
    DEFAULT: "Bob"
FROM: "ubuntu"
MAINTAINER: "RocketBoots"
TAG: "hello-{lower({USER})}"
STEPS:
  - BUILDCONTEXT:
      - SRC: "./build-context/samples/"
      - SRC: "./build-context/install.sh"
      - SRC: "./build-context/default.properties"
    RUN:
      - "{BUILD_CONTEXT_PATH}/install.sh {AUTHOR} {USER}"
    COPY:
      - SRC: "./build-context/conf/"
        DST: "/etc/hello-{lower({USER})}/"
    CONFIG:
      EXPOSE:
        22/tcp:
      ENV:
        MESSAGE: "Hello {USER}!"
      ENTRYPOINT: "bash"
      CMD:
        - "-e"
      LABELS:
        Company: "RocketBoots"
        Author: "{AUTHOR}"
```

Might produce output something like:

```
Build file: ./docker-build.yml

Hello world application

Usage:
    build-tool AUTHOR=AUTHOR [USER=USER]

Arguments:
    author        The name of the author of this image
    user          The person who is being greeted

From 'ubuntu' image, maintained by 'RocketBoots'.
```
