### ISSUE TITLE
Support alternative values for arguments

### ISSUE THREAD

**Issue by brian-bason** [brian-bason/docker-build-tool#28]
Some times an argument value needs to be mapped to a different value. As an example an architecture value of either **amd64** or **arm** should be mapped to <blank> and pi respectively. This will give the user the ability to accept certain values for an argument but be converted to another value for the build.

```
ARGS:
    ARCHITECTURE:
        CHOICE:
            - "amd64"
            - "arm"
        MAPPINGS:
            -  ARG: "REPO_NAME"
               VALUES:
                 amd64: "bee-collector-pipeline"
                 arm: "bee-collector-pipeline-pi"

```
