### ISSUE TITLE
Default argument values not available as environment variables

### ISSUE THREAD

**Issue by johndavidpearce** [brian-bason/docker-build-tool#33]
When an argument is provided with a default value in the `docker-build.yml` file, its default value is not being included as an environment variable available during the build. However if the value is explicitly specified (e.g. by a `VALUE` found in the `~/.docker/build-config.yml` file, or via the `-a ARG=VALUE` command-line argument) then the value is passed into the build environment as expected.

*docker-build.yml*

```
VERSION: "1.0"
FROM: "ubuntu:14.04"
TAG: "test"
ARGS:
  ARG1:
    DEFAULT: "hello!"
STEPS:
  - RUN:
      - "echo Replaced value = {ARG1}"
      - "echo Environment value = ${{ARG1}}"
      - "exit 1"
```

If the above is built, you can see this output:

```
Replaced value = hello!
Environment value = 
```
