### ISSUE TITLE
Feature request: Load arguments from file

### ISSUE THREAD

**Issue by johndavidpearce** [brian-bason/docker-build-tool#38]
Support the reading of argument values from a project-specific file, which is defined in the `docker-build.yml` file. Furthermore, the file path of this argument file should support argument expansion (using command-line arguments). Multiple argument files may be specified. See below:

```yaml
ARGS:
  APP:
    REQUIRED: True
    CHOICES:
      - App1
      - App2
  VERSION:
    DEFAULT: "Default command-line value"
ARGFILES:
  - ./conf/base-config.yml
  - ./conf/{lower({APP})}/app-config.yml
```

Using this method, it allows projects to support build variants (which is already supported through features such as argument mappings) which can now include build-variant-specific arguments.

## Precedence ##

Any *default* values provided in the command-line arguments would be overridden by values in the first argument file, and values in the second argument file would override either default argument values or arguments from the first argument file. However values explicitly provided on the command-line would override everything. So precedence is summarised:

1. Explicitly provided command-line arguments
2. Values found in *argument files*, starting at the last file path and going up.
3. Default values for command-line arguments
